export const BUY = "BUY";
export const DELETE = "DELETE"
export const TOGGLEPREFERITES = "TOGGLEPREFERITES"
export const GETASYNCHCOMICSTHUNK = "GETASYNCHCOMICSTHUNK"
export const EDITASYNCHCOMICTHUNK = "EDITASYNCHCOMICTHUNK"
export const CREATEASYNCHCOMICSTHUNK = "CREATEASYNCHCOMICSTHUNK"
export const LOGIN = "LOGIN"
export const SIGNUP = "SIGNUP"
export const LOGOUT = "LOGOUT"
export const FORMEDITPRODUCT = "FORMEDITPRODUCT"
export const CHANGEINPUT = "CHANGEINPUT"
export const BLURINPUT = "BLURINPUT"
export const AUTHENTICATE = "AUTHENTICATE"

