export const BUY = "BUY";
export const DELETE = "DELETE"
export const TOGGLEPREFERITES = "TOGGLEPREFERITES"
export const GETASYNCHCOMICSTHUNK = "GETASYNCHCOMICSTHUNK"
export const EDITASYNCHCOMICTHUNK = "EDITASYNCHCOMICTHUNK"

export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"